with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"

packages:
  # Inventory service
  github.com/dexguitar/spacecraftory/inventory/internal/repository:
    interfaces:
      InventoryRepository:
  github.com/dexguitar/spacecraftory/inventory/internal/service:
    interfaces:
      InventoryService:

  # Payment service
  github.com/dexguitar/spacecraftory/payment/internal/repository:
    interfaces:
      PaymentRepository:
  github.com/dexguitar/spacecraftory/payment/internal/service:
    interfaces:
      PaymentService:

  # Order service
  github.com/dexguitar/spacecraftory/order/internal/repository:
    interfaces:
      OrderRepository:
  github.com/dexguitar/spacecraftory/order/internal/service:
    interfaces:
      OrderService:
      ProducerService:
      ConsumerService:
  github.com/dexguitar/spacecraftory/order/internal/client:
    interfaces:
      InventoryClient:
      PaymentClient:
