with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True

packages:
  # Inventory service
  github.com/dexguitar/spacecraftory/inventory/internal/repository:
    config:
      include-regex: ".*Repository"
  github.com/dexguitar/spacecraftory/inventory/internal/service:
    config:
      include-regex: ".*Service"

  # Payment service
  github.com/dexguitar/spacecraftory/payment/internal/repository:
    config:
      include-regex: ".*Repository"
  github.com/dexguitar/spacecraftory/payment/internal/service:
    config:
      include-regex: ".*Service"

  # Order service
  github.com/dexguitar/spacecraftory/order/internal/repository:
    config:
      include-regex: ".*Repository"
  github.com/dexguitar/spacecraftory/order/internal/service:
    config:
      include-regex: ".*Service"
  github.com/dexguitar/spacecraftory/order/internal/client:
    config:
      include-regex: ".*Client"
