openapi: 3.0.3
info:
  title: OrderService API
  version: 1.0.0
  description: API for managing spacecraft orders
x-ogen:
  target: ./shared/pkg/openapi/order/v1
  package: order_v1
  clean: true

tags:
  - name: Orders
    description: Operations with orders - creation, payment, retrieval, and cancellation

paths:
  /api/v1/orders:
    $ref: ./paths/order_create.yaml
  /api/v1/orders/{order_uuid}:
    $ref: ./paths/order_by_uuid.yaml
  /api/v1/orders/{order_uuid}/pay:
    $ref: ./paths/order_pay.yaml
  /api/v1/orders/{order_uuid}/cancel:
    $ref: ./paths/order_cancel.yaml
