// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dexguitar/spacecraftory/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// IAMClient is an autogenerated mock type for the IAMClient type
type IAMClient struct {
	mock.Mock
}

type IAMClient_Expecter struct {
	mock *mock.Mock
}

func (_m *IAMClient) EXPECT() *IAMClient_Expecter {
	return &IAMClient_Expecter{mock: &_m.Mock}
}

// WhoAmI provides a mock function with given fields: ctx, sessionUUID
func (_m *IAMClient) WhoAmI(ctx context.Context, sessionUUID string) (*model.Session, *model.User, error) {
	ret := _m.Called(ctx, sessionUUID)

	if len(ret) == 0 {
		panic("no return value specified for WhoAmI")
	}

	var r0 *model.Session
	var r1 *model.User
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Session, *model.User, error)); ok {
		return rf(ctx, sessionUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Session); ok {
		r0 = rf(ctx, sessionUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *model.User); ok {
		r1 = rf(ctx, sessionUUID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.User)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, sessionUUID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IAMClient_WhoAmI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WhoAmI'
type IAMClient_WhoAmI_Call struct {
	*mock.Call
}

// WhoAmI is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionUUID string
func (_e *IAMClient_Expecter) WhoAmI(ctx interface{}, sessionUUID interface{}) *IAMClient_WhoAmI_Call {
	return &IAMClient_WhoAmI_Call{Call: _e.mock.On("WhoAmI", ctx, sessionUUID)}
}

func (_c *IAMClient_WhoAmI_Call) Run(run func(ctx context.Context, sessionUUID string)) *IAMClient_WhoAmI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IAMClient_WhoAmI_Call) Return(_a0 *model.Session, _a1 *model.User, _a2 error) *IAMClient_WhoAmI_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *IAMClient_WhoAmI_Call) RunAndReturn(run func(context.Context, string) (*model.Session, *model.User, error)) *IAMClient_WhoAmI_Call {
	_c.Call.Return(run)
	return _c
}

// NewIAMClient creates a new instance of IAMClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAMClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAMClient {
	mock := &IAMClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
